name: env variables

on: 
  push:
    paths-ignore:
      - random.txt

permissions:
  contents: write 

env:
  WF_ENV: Available to All Jobs
  # WF_ENV: ${ secrets.WF_ENV }} //actually "$"pachi aa aave===>>>{{secrets.WF_ENV }}   # WF_ENV: ${ secrets.GITHUB_TOKEN }}

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push a Random file
        run: |
          pwd
          ls -a
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add random.txt
          git add -A
          git commit -m"Random File" || echo "Nothing else to commit"
          git push
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Avaliable to all steps in log-env job

    steps:
      - name: Log ENV variables
        env:
          STEP_ENV: Avaliable to only this step
        run: |
          echo "WF_ENV:${WF_ENV}" 
          echo "JOB_ENV:${JOB_ENV}" 
          echo "STEP_ENV:${STEP_ENV}"
      - name: Log ENV 2
        run: |
          echo "WF_ENV:${WF_ENV}" 
          echo "JOB_ENV:${JOB_ENV}" 
          echo "STEP_ENV:${STEP_ENV}"

  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV Variables
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION:  ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS:  ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
